### ISSUE TITLE
Can support embedded database such as H2 for Integration Test ?

### ISSUE THREAD

**Issue by zhengyangyong** [ctripcorp/apollo#1104]
Hello,we had use apollo as configuration center for servicecomb, but it seems only support MySQL database, that make CI very heavy, can support any embedded database such as H2 in apollo fat jar like zipkin, then delopyment for dev will be easier

**Comment by nobodyiam** [comment]
Actually apollo does support h2, because we use h2 in integration test...

You may take a look at [ConfigControllerIntegrationTest.java](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/test/java/com/ctrip/framework/apollo/configservice/integration/ConfigControllerIntegrationTest.java) and try to run it locally.

**Comment by zhengyangyong** [comment]
Great! Is `openapi` also enabled in integration test mode ? @nobodyiam

**Comment by nobodyiam** [comment]
Sure, since `openapi` module is embedded in `apollo-portal`, if you run `apollo-portal` in integration mode, the `openapi` module is also enabled.

**Comment by zhengyangyong** [comment]
Thanks!
