### ISSUE TITLE
I am integrating Apollo with Dubbo as Dubbo's configuration center, could the community help me  with it?

### ISSUE THREAD

**Issue by chickenlj** [ctripcorp/apollo#1306]
Hi, I am a developer from Dubbo community. Recently, Dubbo has abstracted a dynamic configuration center, and we want Apollo as one of the implementations. I have tried to give a demo integrating with Apollo, but not sure if it's the best practice. Hope you guys can help me with it.

Here's the demo of integrating with Apollo.
https://github.com/apache/incubator-dubbo/pull/2160/files#diff-f2036c4c26aabd79367138d3b5190589

**Comment by nobodyiam** [comment]
Thanks @chickenlj, I left several comments on https://github.com/apache/incubator-dubbo/pull/2160.

BTW, I have proposed a merge request #1315 so that we could deploy apollo client to maven central repository

**Comment by chickenlj** [comment]
Thanks, thanks for the constructive advice.

> BTW, I have proposed a merge request #1315 so that we could deploy apollo client to maven central repository
That's great, I have seen the SNAPSHOT version already being deployed to the central repo.

**Comment by nobodyiam** [comment]
@chickenlj 

apollo-client is now deployed to maven central repo, [follow this link to see more](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ctrip.framework.apollo%22%20AND%20a%3A%22apollo-client%22)

**Comment by chickenlj** [comment]
> apollo-client is now deployed to maven central repo, follow this link to see more
Awesome!

I have got another question: What if` ConfigService.getConfig('the namespace')` fails to connect to the server when initialize? Has Apollo already considered this scenario? Or do you have any suggestions for how to retry or handle? We don't want Dubbo to fail in the case when Apollo doesn't work.

I'm still not very clear about the way Apollo runs, does it keep a long connection between client or server? Or does it just polls with a fixed schedule?

**Comment by nobodyiam** [comment]
Apollo client has a long connection with server (implemented by http long polling) so that it could get the config update notification in real time. It also has a fixed schedule refresh to make sure the config is up to date if case long polling failed.

If `ConfigService.getConfig('the namespace')` fails to connect to the server during initialization, it will keep retrying in the backend and will update configs and notify client as soon as the connection is established. It will not make dubbo fail in this case and will always return the default value provided when calling getProperty method. It's up to the caller to decide whether the application should crash or not.

You may refer [Apollo配置中心设计#三客户端设计](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E8%AE%BE%E8%AE%A1#%E4%B8%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AE%BE%E8%AE%A1)(in Chinese) for more information on how we design the client side.
