### ISSUE TITLE
How to get current release version from client?

### ISSUE THREAD

**Issue by cirfi** [ctripcorp/apollo#1554]

**Comment by nobodyiam** [comment]
Client will report the release key to tracer everytime the config is updated, see [RemoteConfigRepository](https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigRepository.java#L147)

For spring boot apps, we are considering to write a custom infoContributor so that more information could be seen via /info endpoint.

**Comment by Anilople** [comment]
reference https://github.com/apolloconfig/apollo/issues/5113
