### ISSUE TITLE
多环境的分布式部署

### ISSUE THREAD

**Issue by tanxiaosheng** [ctripcorp/apollo#1834]
现在项目有两套k8s集群，生产环境和开发环境，在分布式部署时发现apollo的开发环境和生产环境的服务实际上部署到同一个k8s集群上了，目前将apollo部署到开发环境所在的k8s集群，这样就导致生产环境k8s集群上的服务应用无法连接到apollo的 meta server，如何将apollo生产环境的config service和admin service部署到生产环境的k8s集群上，并保证portal能连接不同k8s集群的meta呢？

**Comment by nobodyiam** [comment]
多环境部署可以参考[分布式部署指南-1.3 环境](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#13%E7%8E%AF%E5%A2%83)

1. 开发环境和生产环境各有一套config service(meta server)，admin service和config db
2 生产环境部署一套portal和portal db
3. portal需要能同时连上开发环境和生产环境的meta server和admin service，这个要看实际的网络情况的，我们公司是通过专线允许portal单向连接测试环境的meta server和admin service

**Comment by hw-mm-payment** [comment]
最近部署了两套k8环境，分别安装开发环境和生产环境的config server和admin server，在生产环境的k8s集群上部署portal server，配置dev.meta为开发环境k8s的config server的对外IP和端口，启动之后报错，portal server连接的是开发环境admin server 所在pod的ip和端口，由于是两个不同的k8s集群，所以无法连接，需要怎么修改才能正常连接开发环境的admin server呢？

**Comment by tanxiaosheng** [comment]
> 多环境部署可以参考[分布式部署指南-1.3 环境](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#13%E7%8E%AF%E5%A2%83)
> 
> 1. 开发环境和生产环境各有一套config service(meta server)，admin service和config db
>    2 生产环境部署一套portal和portal db
> 2. portal需要能同时连上开发环境和生产环境的meta server和admin service，这个要看实际的网络情况的，我们公司是通过专线允许portal单向连接测试环境的meta server和admin service

**Comment by tanxiaosheng** [comment]
可以通过node ip连接 @nobodyiam

**Comment by nobodyiam** [comment]
可以参考[网络策略](https://github.com/ctripcorp/apollo/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97#14%E7%BD%91%E7%BB%9C%E7%AD%96%E7%95%A5)把admin service的node ip注册到meta server，从而portal可以通过node ip连接

**Comment by huzhou520** [comment]
我们有两套k8环境，分别安装开发环境和生产环境的config server和admin server，现在需要在一台单独的虚拟机上部署portal来统一管理，这台虚拟机到生产和测试环境的k8s网络是能通的。但在虚拟机上启动portal的时候报错。 错误信息如下:

2019-03-07 16:50:41.910 ERROR 14866 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: PRO, meta server address: http://10.100.65.149:8080

com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://10.100.65.149:8080

**Comment by nobodyiam** [comment]
到portal的机器上 curl 一下 `http://10.100.65.149:8080/services/admin`

**Comment by huzhou520** [comment]
这边可以了哈
