### ISSUE TITLE
  Why not communicate in English?

### ISSUE THREAD

**Issue by master-starcloud** [ctripcorp/apollo#1875]
If this project wants to become international, it will be better to communicate in English. So submit Issues for English...

**Comment by nobodyiam** [comment]
Thanks for your suggestion, currently we don't enforce communication in English because most of the users are based in China and they tend to use Chinese to describe their issues or suggestions. What we really want is to solve their problems, so we don't like to add more burden on them by enforcing communication in English.

However, as you mentioned, this project will become international, so it will be better to post issues in English so that future users could reference these issues for knowledge. And this is what we will encourage in the future. 

Also there are many i18n areas for Apollo to improve, e.g. wiki, ui, messages, which we will put more effort on.

**Comment by master-starcloud** [comment]
@nobodyiam yeah ,I understand
