### ISSUE TITLE
Support Eureka Authentication

### ISSUE THREAD

**Issue by nobodyiam** [ctripcorp/apollo#3807]
**Is your feature request related to a problem? Please describe.**
Though not recommended, there are cases apollo-configservice would be deployed in internet instead of intranet, e.g. apollo-demo site.
In these cases, we need to support user to config the eureka authentication information to avoid malicious services registered to the eureka.

**Describe the solution you'd like**
Configure eureka related paths with authentication required.

**Describe alternatives you've considered**
Other alternatives are welcome.

**Additional context**

**Comment by vdisk-group** [comment]
it seems better to add a `authentication-gateway` reverse proxy the `apollo-configservice`, instead of deployed `apollo-configservice` in internet directly.  
we could deploy the `apollo-configservice` and `apollo-adminservice` on the intranet, and only expose the `authentication-gateway` and `apollo-portal` to the internet.

**Comment by nobodyiam** [comment]
I agree it's a good idea to add an `authentication-gateway` reverse proxy with whitelisted paths of `/configs/**` and `/notifications/**`.

Let's keep this issue open for a while to see if there are actual use cases.
