### ISSUE TITLE
k8s里 admin-service在eureka中的状态为	OUT_OF_SERVICE (1)

### ISSUE THREAD

**Issue by jhonone** [ctripcorp/apollo#3826]
![image](https://user-images.githubusercontent.com/33852386/125602658-11e984cb-bbcb-4684-8bc5-077e89836412.png)

protal的日志
![image](https://user-images.githubusercontent.com/33852386/125602881-47f71c88-1032-4a1e-9e03-3507f32d0d7a.png)

**Comment by programming-pupil** [comment]
解决了吗？我也是这问题，一天啦！

**Comment by mapix** [comment]
可以检查一下 admin-service 里边有没有 

`Ignoring onDemand update due to rate limiter`

如果有的话大概率是因为令牌问题。可以在启动容器的 JAVA_OPTS  中注入, 来避免令牌导致状态无法更新的问题

` -Deureka.client.instance-info-replication-interval-seconds=24`

参考这篇救命贴：
https://blog.csdn.net/xiao_jun_0820/article/details/82823602

**Comment by wkclz** [comment]
@mapix  你说的这个现象，确实没问题，但好像解决不了问题，以下是新发现：
1. eureka.client.instance-info-replication-interval-seconds=1 之后，allowedRatePerMinute 就是120 了，仍然会被限流。
2. 限流参数为：burstSize=2， 并且是写死的，没找到相关配置
3. 扩大内存之后（无意之间想扩大内存看看效果），神奇的正常了，分析日志发现有三个阶段：
  3.1 启动之初，仍然是 Ignoring onDemand update due to rate limiter
  3.2 随之是报错无法解析 host 导致无法注册（用了容器，svc 还没解析，猜想是进入了注册重试）
  3.3 注册成功，一切恢复正常
4. 扩大内存前（相比扩大内存后），日志分析：
  4.1 启动之初，仍然是 Ignoring onDemand update due to rate limiter
  4.2 启动成功，注册成功，但状态为 OUT_OF_SERVICE
  4.3 没有发现新的心跳再更新状态

为什么我会关注这个问题：
发现配置变更，应用需要1~3分钟才响应，从应用端，应用客户端版本，均没找到问题。所以重新搭建了一套 apollo, 发现以上问题

问题猜想：
1. 内存不足导致注册成功（状态失败），又没重试（疑问：为什么不再重试了）
2. 限流的 burstSize 不合理，导致状态无法变更

解决方案：
1. 加内存（2G 时发现的问题，4G 之后正常了）
2. 调整 burstSize （自己未测试，需要重新编译 eureka-client, 应该能解决）
3. 期待 apollo 能给个解决方案。应该有更优雅的方式。期待换掉eureka

神坑一个，几个 issues 都没解决。有新发现我再上来。

**Comment by wkclz** [comment]
进一步实验：
1. 限流问题通过改 burstSize 解决了，问题仍然没解决。
2. 扩大内存，正常启动也是概率事件。追了源码，发现状态一直取上一次，一直 OUT_OF_SERVICE
3. 问题还需要进一步定位，但没耐心了，什么年代了还 Eureka, 于是换了 k8s 作为注册中心。目前还发现了设计上的坑点，待继续验证。要年后了，不卷

**Comment by wkclz** [comment]
后续：
2.0.1 使用 kubernetes 作为注册中心，支持 在配置，或 ServerConfig 表，添加 apollo.config-service.url 参数以辅助发现 apollo-confingservice
成功摆脱了 Eureka （没有继续尝试其他配置中心）

这里设计的坑点：其他的都是去注册中心找 apollo-confingservice，到了 kubernetes 也应该去 kubernetes  找， 而不是手动配置。配置能解决，但也不优雅

不过，database discovery 是一个解决方案吧，在文档里面看到了，但在 Tag 里面还没发布 2.1.0 版本
@nobodyiam
