### ISSUE TITLE
项目启动成功后获取配置日志中给出信息  Long polling response: 304

### ISSUE THREAD

**Issue by jzsn** [ctripcorp/apollo#982]
Springboot 接入的Apollo 配置中心 ，项目成功启动后 日志中给出信息   Long polling response: 304  不知道是什么原因啊 求大神科普

**Comment by zhangyicou** [comment]
304表示没有新发布的配置，是正常返回。 看看官方文档，有说明发自我的华为手机-------- 原始邮件 --------主题：[ctripcorp/apollo] 项目启动成功后获取配置日志中给出信息 Long polling response: 304 (#982)发件人：jzsn 收件人：ctripcorp/apollo 抄送：Subscribed Springboot 接入的Apollo 配置中心 ，项目成功启动后 日志中给出信息   Long polling response: 304  不知道是什么原因啊 求大神科普

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ctripcorp/apollo","title":"ctripcorp/apollo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ctripcorp/apollo"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"项目启动成功后获取配置日志中给出信息  Long polling response: 304 (#982)"}],"action":{"name":"View Issue","url":"https://github.com/ctripcorp/apollo/issues/982"}}}

**Comment by jzsn** [comment]
谢谢 ， 我自己添加配置发布后 日志中已经没有这个信息了

**Comment by nobodyiam** [comment]
@jzsn 304是HTTP状态码 Not Modified 的意思，是正常的状态码，在打开debug日志时才会输出，调一下日志级别即可。

**Comment by nobodyiam** [comment]
case先关闭了，如还有问题，可以提供更多信息，或进群交流。
